### ISSUE TITLE
create pinout markup based on mapping.md

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2144]
At the moment we manually maintain two files - markup.md pinout and mapping.yaml for .ini

it should be one source of truth, potentially also generating some C header to be used for engine configs

**Comment by rusefillc** [comment]
we have machine-readable https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/mapping.yaml

which overlaps with manually supported https://github.com/rusefi/rusefi/wiki/Hardware-Proteus-Wiring-v03

i would prefer the table in https://github.com/rusefi/rusefi/wiki/Hardware-Proteus-Wiring-v03 in to be generated based on  https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/mapping.yaml

 https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/mapping.yaml would probably need more data to generated section of https://github.com/rusefi/rusefi/wiki/Hardware-Proteus-Wiring-v03

**Comment by rusefillc** [comment]
there is also different a bit related https://github.com/rusefi/rusefi_documentation/issues/118 in different GF because reasons.

**Comment by chuckwagoncomputing** [comment]
Format proposal:

```
outputs:
  # TLE8888 injector channels
  - id: TLE8888_PIN_1
    pin_number: 37 
    function: Injector 1
    type: inj  
    color: grey right 

  - id: TLE8888_PIN_2
    pin_number: 38 
    function: Injector 2 ```

**Comment by rusefillc** [comment]
My name is... (fill in) and I approve this proposal!

**Comment by rusefillc** [comment]
drama is to change all mapping files and java code which reads it already in the same PR

**Comment by mck1117** [comment]
oh, and we can't really change the existing pin names in the ini, because TS stores them by name, not by binary value

**Comment by chuckwagoncomputing** [comment]
The name being e.g. "37 - Injector #1"?
Or TLE8888_PIN_1?

**Comment by mck1117** [comment]
the string "37 - Injector #1"

**Comment by chuckwagoncomputing** [comment]
I was hoping we could rebuild that in Java, but it looks like not everything follows the same pattern.

**Comment by rusefillc** [comment]
because not machine readable thus this ticket :)

**Comment by chuckwagoncomputing** [comment]
So I guess we need something like this:
```
outputs:
  # TLE8888 injector channels
  - id: TLE8888_PIN_1
    pin_number: 37
    ts_name: 37 - Injector 1
    function: Injector 1
    type: inj
    color: grey right
```
I don't like the redundant data but I guess it can't be helped without messing up the ini format.

**Comment by chuckwagoncomputing** [comment]
And just so we're clear, the redundancy is necessary because of stuff like this:
```
  # J2
  GPIOA_15: "AUX J2 PA15"
  GPIOB_8:  "AUX J2 PB8"
  GPIOB_9:  "AUX J2 PB9"
  GPIOC_12: "AUX J2 PC12"
  GPIOE_0:  "AUX J6 PE0"
  GPIOE_6:  "AUX J10 PE6"
  GPIOE_5:  "AUX J11 PE5"
  GPIOB_7:  "AUX J18 PB7"

  GPIOB_0: "AUX AV8 reuse"
  GPIOB_1: "AUX AV9 reuse"
  GPIOA_4: "AUX AV10 reuse"
  GPIOC_4: "AUX AV6 reuse"
```

**Comment by rusefillc** [comment]
I do not follow

.ini is already generated based on mapping.yaml?

**Comment by chuckwagoncomputing** [comment]
If I understand what Matt said, yes, and we can't change the names in the ini without breaking user's configs. I hoped we could reconstruct the name string from the old format using the 'pin_number' and 'function' fields, but not all pins follow the same format, especially across different boards. Therefore we need to retain the name string from the old format, in the new format.
The reason we have the pin_number and the function fields separated in the new format is for constructing the table in the md, as it appears now. We could change the format of the table, but I'm already brainstorming something else this yaml could be used for, which would need the pin number as its own field.

**Comment by mck1117** [comment]
we could just put a "tunerstudio pin name" in the yaml?

**Comment by chuckwagoncomputing** [comment]
> ```
> outputs:
>   # TLE8888 injector channels
>   - id: TLE8888_PIN_1
>     pin_number: 37
>     ts_name: 37 - Injector 1
>     function: Injector 1
>     type: inj
>     color: grey right
> ```

**Comment by chuckwagoncomputing** [comment]
I forgot that name and function are separate table columns, so we need even more redundancy:

```
- id: TLE8888_PIN_1
    pin_number: 37
    name: Injector 1
    function: Injector 1
    ts_name: 37 - Injector 1
    type: inj
    color: grey right
```

**Comment by chuckwagoncomputing** [comment]
More confusion:
Some ts names, e.g. "23 - AN temp 2" are assigned to multiple pin names, in this case "GPIOA_1" and "EFI_ADC_1", in different sections.

**Comment by chuckwagoncomputing** [comment]
This does not map 1:1 with the table, which has only one row for 23.

**Comment by chuckwagoncomputing** [comment]
The wiki table is a connector pin map, while the yaml is a MCU pin map. I think we should have a separate yaml for every connector that maps the IDs in mapping.yaml to pin numbers. The MRE for example, would have one for the main connector, and others if we wanted tables for the other connectors, such as J2 and J8.

**Comment by chuckwagoncomputing** [comment]
```
outputs:
  # TLE8888 injector channels
  - id: TLE8888_PIN_1
    function: Injector 1
    ts_name: 37 - Injector 1
    type: inj

  - id: TLE8888_PIN_2
    function: Injector 2
    ts_name: 38 - Injector 1
    type: inj
```

```
pins:
  - pin: 37
    id: TLE8888_PIN_1
    color: grey right

  - pin: 38
    id: TLE8888_PIN_2
    color: grey
```

**Comment by mck1117** [comment]
Is it worth inverting the structure?  Declare a list of pins, and for each one, state whether it's a [outputs, event_inputs, switch_inputs, analog_inputs] (multiple allowed)?

**Comment by chuckwagoncomputing** [comment]
I was so close to thinking of that. :)
```
pins:
  - pin: 1
    id: EFI_ADC_11
    color: white right
    function: 12V Supply from main relay output, see also pin #29
    ts_name: Battery Sense
    type: 12V
    class: analog_inputs

  # default Idle Air Control TLE8888 high current low side: VVT2 TLE8888_OUT5
  - pin: 3
    id: TLE8888_PIN_5
    color: white
    function: Idle solenoid
    ts_name: 3 - Lowside 2
    type: ls
    class: outputs

...

  - pin: 18
    id: [GPIOA_0, EFI_ADC_0]
    color: red
    function: CLT sensor
    ts_name: 18 - AN temp 1
    type: at
    class: [switch_inputs, analog_inputs]
```

I like that the best of anything yet. It'll take some care on my part while converting to not get things switched around, so we can assume that the first element in 'id' goes with the first element in 'class' and so on.
