### ISSUE TITLE
gcc12 gcc 12

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5031]
time flies https://github.com/rusefi/rusefi/commit/944f64f3b1070a58db266b6a9e97eda8610c04d6

they now have gcc12

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/216728384-b6e2c6dd-807a-4c77-883b-9c6dcbbc5a11.png)

**Comment by rusefillc** [comment]
Full disclosure this change is an attempt to address https://github.com/rusefi/rusefi/issues/5354

**Comment by rusefillc** [comment]
```
    - name: Acquire GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.3.Rel1'
```
