### ISSUE TITLE
github artifact separate full bundle from autoupdate bundle

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6049]
at the main repo action seems to zip full and autoupdate bundle together into one artifact, and then upload autoupdate artifact once again separately

would be much nicer to have separate artifact for full bundle and separate artifact for autoupdate

would regexp allow "not ending with autoupdate" condition to accomplish that?

```
    - name: Upload bundle artifact
      if: ${{ env.full == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: rusefi_bundle_${{matrix.build-target}}.zip
        path: ./artifacts/rusefi_bundle*.zip

    - name: Upload github action autoupdate artifact
      if: ${{ env.full == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: rusefi_bundle_${{matrix.build-target}}_autoupdate.zip
        path: ./artifacts/rusefi_bundle_${{matrix.build-target}}_autoupdate.zip
```
